### ISSUE TITLE
[Bug]: mempool websocket connection lost

### ISSUE THREAD

**Issue by vforvilela** [Murray-Rothbot/service-blockchain#18] opened 2023-01-27 01:15 UTC
The websocket connection is lost and not recovered after an internet crash.

To reproduce:
1. Run the blockchain service
2. Turn off the internet
3. Wait a few minutes
4. Turn it on again
5. The websocket connection is lost forever

Before the internet crash (is possible to see the websocket "pings"):

![image](https://user-images.githubusercontent.com/80433106/214985687-b637496e-9039-4c68-b179-763eec953cce.png)

During the crash:

![image](https://user-images.githubusercontent.com/80433106/214986327-b1e8f637-f8fb-4517-8ace-539b2392bb3d.png)

After the crash:

![image](https://user-images.githubusercontent.com/80433106/214985881-abb738e7-1f8d-4900-bf98-1737a870a34c.png)

**Comment by MiguelMedeiros** [comment] 2024-03-09 19:08
Not able to reproduce it. Will close this PR it for now.

**Closed by MiguelMedeiros** 2024-03-09 19:08 UTC
